// angular-front/src/app/view/home/home.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  @Input() msg: string
  subtitle: string = 'Angular'
  
  constructor() { }

  ngOnInit(): void {
  }

  resetSubtitle(): void {
    this.subtitle = 'Angular'
  }

}

<h1>{{ msg }}</h1>
<h2>{{ subtitle }}</h2>

<input type="text" [(ngModel)]="subtitle">
<button (click)="resetSubtitle()">Reset subtitle</button>

// react-front/src/view/home/Home.jsx
import React, {useState} from "react";
import "./Home.css";

// function Home() {
//     return (
//         <h1>Home</h1>
//       );
// }
// export default Home;

// export default function() {
//     return (
//         <h1>Home</h1>
//       );
// }

export default (props) => {
  let [subtitle, setSubtitle] = useState("React (Hooks)")

  function resetSubtitle() {
    setSubtitle("React (Hooks)")
  }

  return (
    <div className="home">
      <h1>{ props.msg}</h1>
      <h2>{ subtitle }</h2>
      
      <input type="text" value={ subtitle } onChange={ e => setSubtitle(e.target.value) } />
      <button onClick={ resetSubtitle }>Reset subtitle</button>
    </div>
  );
};
