// react-front/src/view/home/Home.jsx
import React, {useState} from "react";
import "./Home.css";

// function Home() {
//     return (
//         <h1>Home</h1>
//       );
// }
// export default Home;

// export default function() {
//     return (
//         <h1>Home</h1>
//       );
// }

export default (props) => {
  let [subtitle, setSubtitle] = useState("React (Hooks)")

  function resetSubtitle() {
    setSubtitle("React (Hooks)")
  }

  return (
    <div className="home">
      <h1>{ props.msg}</h1>
      <h2>{ subtitle }</h2>
      
      <input type="text" value={ subtitle } onChange={ e => setSubtitle(e.target.value) } />
      <button onClick={ resetSubtitle }>Reset subtitle</button>
    </div>
  );
};

// vue-front/src/view/home/Home.vue
<template>
  <div>
    <h1>{{ msg }}</h1>
    <h2>{{ subtitle }}</h2>

    <input type="text" v-model="subtitle">
    <button @click="resetSubtitle">Reset subtitle</button>
  </div>
</template>

<script>
export default {
  props: ['msg'],
  data: function() {
    return {
      subtitle: 'Vue'
    }
  },
  methods: {
    resetSubtitle() {
      this.subtitle = 'vue'
    }
  }
}
</script>

<style>

</style>
